### ISSUE TITLE
子集不可见菜单，交互展示有问题

### ISSUE THREAD

**Issue by rodchen-king** [CareyToboo/ovine#18]
## 问题描述：
关于路由那一块，列表路由下面有一个详情页面，详情页的路由不会再左侧菜单显示，而且打开详情页面，左侧菜单打开的位置是列表页面。

![{6NR(WMEIBLZOT MO44$%$N](https://user-images.githubusercontent.com/19780441/88611012-b658f880-d0ba-11ea-9d18-65429dd653ec.png)

![0FGM67RRZ)5U26D@OGXST40](https://user-images.githubusercontent.com/19780441/88611038-c5d84180-d0ba-11ea-82cd-ded4447f6077.png)

## 期望结果：
嗯，就是列表主页面下面有子集菜单，
1. 左侧菜单不需要展示，
2. 点击子集菜单【例如详情页面】，菜单展示定位到列表页面

**Comment by CareyToboo** [comment]
该问题在 0.1.0 版本中已经修复。
