### ISSUE TITLE
不错的项目， 但是amis editor没有集成进来嘛

### ISSUE THREAD

**Issue by darkz1984** [CareyToboo/ovine#26]
不错的项目， 但是amis editor没有集成进来嘛
只能json编辑， 缺少了一层可视化编辑了

**Comment by CareyToboo** [comment]
可视化编辑是未来的一个方向，amis-editor有很多不好的地方，觉得没有必要引进来。所以单独在写一个仿amis-editor 的编辑器，[ovine-editor](https://ovine.igroupes.com/demo/craft) 可以先体验一下。弄好了之后，会接入Ovine的。

**Comment by CareyToboo** [comment]
由于编辑研发太耗时，已经接入 amis-editor 编辑器了。可以在 官网 demo 项目进行体验了。预计下月发布正式版本。

**Comment by darkz1984** [comment]
感谢大佬贡献
