### ISSUE TITLE
路由到具体页面时如何接收参数？

### ISSUE THREAD

**Issue by anlinew** [CareyToboo/ovine#27]
路由中配置如下“启动应用”处：
{
      label: 'DEMO应用',
      icon: 'fa fa-paint-brush',
      nodePath: 'application',
      children: [
        {
          label: '热更新管理',
          nodePath: 'hot', // 对应 src/pages/application/hot
        },
        {
          label: '文档管理',
          nodePath: 'doc', // 对应 src/pages/application/doc
        },
       {
          label: '启动应用',
          **appcode: 'demo/demo1',**
          nodePath: 'startapp', // 对应 src/pages/application/startapp
        },
      ],
    },

比如我想在startapp页面获取到appcode值，需要怎么处理，谢谢

**Comment by CareyToboo** [comment]
startapp 是一个自定义页面的话。

对应的文件： `src/pages/application/startapp.jsx`

```jsx
export default (props) => {
    console.log('props===>', props) // 路由相关的内容， 都在props里
    return <div>123</div>
}
```

其他自定义文件里，比如: `src/components/xxx.jsx`
```jsx
import { usePresetContext } from '@core/routes/route'
const Button = () => {
    const routeData = usePresetContext()
    console.log('routeData===>', routeData)
}
```
