### ISSUE TITLE
在crud里,批量的API获取expired是失去功能

### ISSUE THREAD

**Issue by xuhandong18** [CareyToboo/ovine#35]
缓存功能是有效的，但在crud的table里，如果每一行都要用API获取数据的话， 就会并发，缓存就等于没有了.
比如: 使用了CRUD里columns使用quickEdit, 然后type= select使用了source.  所有source获取会由于并发一起触发了,但这时还没缓存,所以最终都真实调用API了.
而AMIS官方的案例是解决了这个问题的,如: https://baidu.gitee.io/amis/docs/types/api?page=1#%E9%85%8D%E7%BD%AE%E6%8E%A5%E5%8F%A3%E7%BC%93%E5%AD%98

**Comment by CareyToboo** [comment]
在 0.1.0 版本，`request` 模块添加了 `cache`  请求数据缓存毫秒参数，可以解决该问题。
