### ISSUE TITLE
增加amis内置组件的国际化配置入口

### ISSUE THREAD

**Issue by hambers** [CareyToboo/ovine#37]
https://github.com/zimo888/amis-tutorial/blob/master/src/i18n/amisLocaleRegister.ts

如上，amis支持内置组件的label文本的国际化配置，建议ovine也新增配置入口。用以满足对amis内置组件的label文本的语言定制

**Comment by CareyToboo** [comment]
该功能已经在0.1.0 版本添加。文档地址： https://ovine.igroupes.com/org/docs/advance/configurations#%E5%BA%94%E7%94%A8%E9%85%8D%E7%BD%AE

![image](https://user-images.githubusercontent.com/15522313/104173048-2d533500-5440-11eb-92eb-045659d55f61.png)

**Comment by hambers** [comment]
//amis.js

export const amis = {
  locale: 'en',
  definitions, // ovine 扩展可用全局的定义，使用 $ref 引用
}


这样配置后，内置组件依然是中文。求大神指点...

![image](https://user-images.githubusercontent.com/6118789/105842289-e9038f80-6010-11eb-804f-dee02a5d8519.png)
