### ISSUE TITLE
功能很全面

### ISSUE THREAD

**Issue by henrry007** [CareyToboo/ovine#4]
功能很全面，加油，谢谢分享

**Comment by CareyToboo** [comment]
后续会逐渐添加一些核心功能。欢迎关注～～

**Comment by xiusin** [comment]
我构建的项目怎么就三个菜单

**Comment by CareyToboo** [comment]
@xiusin Ovine只是一个Admin框架，构建的DEMO项目只是用来演示的，具体功能要照着文档自己写的。

**Comment by xiusin** [comment]
@CareyToboo 我以为可以直接拿到你演示的框架呢， 那个全呀 
![image](https://user-images.githubusercontent.com/36065131/86571132-8c248700-bfa3-11ea-8a7e-74d97e3a5342.png)

**Comment by CareyToboo** [comment]
demo 的结构能拿到的。不然从头写，多累啊。而且有些配置还是蛮独特的，不好摸清楚。 初始化项目的时候，你可以选 `demo` 就能拿到 演示的所有代码。----强烈建议正式使用的话，加下Q群。这边任何问题第一时间支持。

![image](https://user-images.githubusercontent.com/15522313/86590789-de28d500-bfc2-11ea-8f55-d20f3ea41d65.png)
