### ISSUE TITLE
tab中页面的筛选条件会在开另外页面的时候被重置掉

### ISSUE THREAD

**Issue by fiattt** [CareyToboo/ovine#41]
ovine版本：0.1.0有此问题（查看线上demo也有此问题）

![7B7C42B04D690A3DD4352E9139AB8C90](https://user-images.githubusercontent.com/1531440/104263820-4ce07100-54c5-11eb-8548-e74fb451e9a0.gif)

**Comment by CareyToboo** [comment]
此问题已经修复了，下个版本就好了。

**Comment by CareyToboo** [comment]
新版本中已修复。
