### ISSUE TITLE
打包时ovine/dll支持配置cdn地址

### ISSUE THREAD

**Issue by MaxToby** [CareyToboo/ovine#43]
构建时支持配置ovine/dll请求地址，方便部署在cdn节点。

**Comment by CareyToboo** [comment]
`v0.1.2`已经支持 [文档地址](https://ovine.igroupes.com/org/docs/advance/configurations#%E7%BC%96%E8%AF%91%E9%85%8D%E7%BD%AE) 配置 `dll: {xxx}` 相关地址即可。
