### ISSUE TITLE
同一个表单同时缓存多个接口，表单中的下拉选项数据是同一个

### ISSUE THREAD

**Issue by gitnote-images** [CareyToboo/ovine#44]
api配置：
![image](https://user-images.githubusercontent.com/56667336/107169588-39a7bf00-69f9-11eb-9314-f563994865d7.png)

页面显示：
![image](https://user-images.githubusercontent.com/56667336/107169617-4cba8f00-69f9-11eb-889d-fb489097666a.png)
![image](https://user-images.githubusercontent.com/56667336/107169634-56dc8d80-69f9-11eb-8026-72247cba5085.png)
![image](https://user-images.githubusercontent.com/56667336/107169647-5fcd5f00-69f9-11eb-8128-ffa7c856a2ab.png)

**Comment by CareyToboo** [comment]
新版本中已修复。
