### ISSUE TITLE
按照你的方法新建页面，为啥不展示在菜单中呢。。

### ISSUE THREAD

**Issue by pershineli** [CareyToboo/ovine#5]
按照你的方法新建页面，为啥不展示在菜单中呢。。

**Comment by CareyToboo** [comment]
因为每一个页面都是有权限控制的。新加的页面（默认是无访问权限的），因此需要侧边栏设置一下权限，刷新就能显示了。

**Comment by pershineli** [comment]
那我找一下侧边栏权限设置是在哪个文件中。。

**Comment by pershineli** [comment]
没在代码中来设置，而是在右上角的设置按钮点开的功能里来配置的。。让我找了半天。。好囧

**Comment by pershineli** [comment]
如果我把项目部署后需要别人也能看到新加的功能，总不能让每个人都去配置权限吧，应该是有统一的权限处理吧？

**Comment by CareyToboo** [comment]
对，右上角设置按钮那个，是开发时方便测试使用的。系统中，有一个集中权限管理的地方,`/system/user_limit` 权限管理表。权限这块也比较复杂，具体使用方式也没来得及写文档，目前开源出来的是一个demo应用，现在还在继续封装为npm包，使用会更方便些。 我建了一个RT交流QQ群：1037291990。欢迎加入，在讨论细节。

**Comment by pershineli** [comment]
太好了，我加群沟通下，多谢

**Comment by CareyToboo** [comment]
新版本不存在这个问题，我先关闭这个issue.
