### ISSUE TITLE
lib-crud组件的排序图标显示有问题

### ISSUE THREAD

**Issue by chenchi2038** [CareyToboo/ovine#51]
使用`lib-crud`组件的表格模式，在其中一列上配置`sortable: true`，点击切换排序方式时，排序图标未正常切换。

![image](https://user-images.githubusercontent.com/6770238/113822549-26725f00-97b0-11eb-8b06-4ac071af9ea4.png)

**Comment by CareyToboo** [comment]
0.1.3 版本已修复。
