### ISSUE TITLE
配置路由不生效，请教

### ISSUE THREAD

**Issue by a2a111** [CareyToboo/ovine#55]
参考教程https://ovine.igroupes.com/org/docs/guides/start
安装了demo，测试修改路由，增加了自己的路由
`{
      label: 'DEMO应用',
      icon: 'fa fa-paint-brush',
      nodePath: 'application',
      children: [
        {
          label: '热更新管理',
          nodePath: 'hot', // 对应 src/pages/application/hot
        },
        {
          label: '文档管理',
          nodePath: 'doc', // 对应 src/pages/application/doc
        },
        {
          label: '天马',
          nodePath: 'pegasus', // 对应 src/pages/application/doc
        },
      ],
    },`
在pages的application目录下增加了pegasus文件夹，拷贝了hot的index.js等3个文件进去
运行的yarn ovine dev命令
刷新却找不到自己的路由，在demo下还是只有热更新管理和文档管理两个导航，不知道什么原因，求助作者或者各位大佬！

**Comment by a2a111** [comment]
我如果在npx @ovine/init@^0.1.0 init my-app执行完之后修改代码，加入自己的路由{ label: '天马', nodePath: 'pegasus', // 对应 src/pages/application/doc }，
然后执行
cd my-app # 切换到生成的项目文件夹下
yarn install # 安装项目依赖
yarn start # 启动项目
自己的路由就能生效，不知道是yarn ovine dev哪里有问题没有更新路由，或者是我有啥缓存没清空。。请大佬们指教

**Comment by CareyToboo** [comment]
新增加/或者编辑路由， 会发现文件找不到，是会有这个情况。 编辑或者增加路由后，'yarn start' 重启一下即可。要么就一次性把侧边栏设计好。 每次启动用 'yarn start' 就行
