### ISSUE TITLE
编译出来的dist目录太大，有50M

### ISSUE THREAD

**Issue by ChungTak** [CareyToboo/ovine#66]
我是根据快速开始"npx @ovine/init@^0.1.0 init my-app"创建项目安装依赖后，运行 npm run build
生成的dist有50M多～生产下这么大无法很难投入使用，0.1.3和0.1.4-alpha都试过
其中最大是 dist/chunks/app_vendor_1de5a3.js 占12M ，对应的app_vendor_1de5a3.js.map 14M.

我从网站的案例项目 http://ovine.igroupes.com/demo/login  中抓包，发现这个在线演示的chunks/app_vendor_xxx.js才几百k
请问怎样才能把编译出来的dist变成这样小?

**Comment by ChungTak** [comment]
重新弄了几次终于发现问题，我之前安装依赖是用 npm install  打包出来50M
改为用yarn 安装依赖后 打包出来就正常了～～ 
很奇怪`～怎么 npm和yarn打包出来差别这么大，估计打包脚本打了npm中多余的东西

**Comment by CareyToboo** [comment]
哦，其实细节我不太清楚，按道理说npm与 yarn 应该是一样的。但是因为自己一直用yarn，没怎么测试npm ～～
